README.md
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/README.md.gotmpl
charts/backstage/values.schema.json
charts/backstage/values.schema.tmpl.json

update links and version to 2.13.0
N/A
https://issues.redhat.com/browse/RHIDP-1020
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

update links and version to 2.13.0

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Relates to: https://issues.redhat.com/browse/RHIDP-1332

fix: increase default size of dynamic-plugins-root volume

---

charts/backstage/Chart.lock
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json

feat: update backstage chart to 1.9.1

---

charts/backstage/Chart.yaml
charts/backstage/templates/_helpers.tpl
charts/backstage/templates/secrets.yaml

The generated backend auth secret and the values.yaml file seem to be run under different contexts which will not allow the use of `common.names.fullname` to get the name of the current release of the chart. The secret will always grab the name of the redhat-developer-hub chart. So instead we should use the `.Release.Name` which will always be the release name for both.

fix: generated secret name should follow release name

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/templates/tests/test-connection.yaml
charts/backstage/values.yaml
ct-install.yaml

Updates the Helm chart to address issues identified by using the SNYK scanning tool, mostly updating the `securityContext` settings on the containers/pods to reduce the attach surface, and also adding requests/limits for the cpu and memory.
Addresses https://issues.redhat.com/browse/RHIDP-1690

chore: RHIDP-1690: Fix SNYK findings

---

.pre-commit/jsonschema-dereference.py
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json

jinja2.Template is called with no autoescape argument (autoescaping is disabled by default). This increases
the risk of Cross-Site Scripting (XSS) attacks.

fix: Jinja auto-escape is set to false

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Backstage injects the config into a javascript file in the dist/static directory in the running instance, which is part of the root filesystem. Until we can fix this we will need the root filesystem to be writable

fix: RHIDP-2974: Revert readOnlyRootFilesystem in values.yaml

---

.github/workflows/bump-version.yml

`xt0rted/slash-command-action` uses deprecated Node.js versions- I did try opening a PR to the action to update the Node.js versions used but it has had no traction.
As such, this PR replaces the logic with `actions/github-script` and `create-or-update-comment`. Both of these actions are more actively maintained.
Note that this only impacts the [bump-version.yml](https://github.com/redhat-developer/rhdh-chart/blob/main/.github/workflows/bump-version.yml) workflow.

chore(ci): replace usage of slash-command-action

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/templates/dynamic-plugins-configmap.yaml
charts/backstage/values.schema.json
charts/backstage/values.yaml

The dynamic-plugins configmap currently has a hard-coded name of 'dynamic-plugins' which prevents having two Developer Hub installations in the same namespace.
This pull request updates the name of the 'dynamic-plugins' configmap to include the name of the release such as '<release>-dynamic-plugins' which will alleviate this issue and allow multiple installations of Developer Hub per namespace using Helm.
https://issues.redhat.com/browse/RHIDP-3048

chore: RHIDP-3048: Add release name to dynamic-plugins configmap name

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

For secure container registry we need a `auth.json` file that contains auth tokens. The file is stored as a secret like
```
oc create secret generic dynamic-plugins-registry-auth --from-file=~/.config/containers/auth.json
```
It is then picked up by `skopeo` during the dynamic plugin install process.
Accompanying PR for dynamic plugins:
https://github.com/janus-idp/backstage-showcase/pull/1479

Add volumeMount for dynamic-plugins-registry-auth

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Update the audit log persistent volume mount path to be consistent with the path that the audit logs are being written to by default https://github.com/janus-idp/backstage-showcase/blob/main/packages/backend/src/logger/customLogger.ts#L68-L70
I have manually tested this via Clean Install and Upgrade from previous non-working Helm Install and both showed the correct behavior without any upgrade errors.

fix: RHDHBUGS-98: Update audit log persistent volume mount path

---

charts/backstage/Chart.lock
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

update backstage chart to 2.1.0
[RHIDP-4912](https://issues.redhat.com/browse/RHIDP-4912)
Motivation is to include [this change](https://github.com/backstage/charts/pull/228) that supports configuring the port under serviceMonitor.
* This is required to configure the port for OpenTelemetry

chore: update backstage chart to 2.1.0

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Adds extra port to expose the metrics reported by OpenTelemetry
* Note that the metrics are disabled by default
[RHIDP-4912](https://issues.redhat.com/browse/RHIDP-4912)

feat: add support for exposing OpenTelemetry metrics

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.yaml

Startup probe settings seem to have been added in the upstream Backstage Chart
in [1], but the current settings do not allow the RHDH Chart for the
liveness probe to be triggered sufficiently enough for the app to be
considered live.
This adjust such settings by accounting for the worst case scenario
where the application might take a bit long to start.
This also aligns the probe endpoints with the upstream chart.
[1] backstage/charts#216
- Fixes https://issues.redhat.com/browse/RHIDP-5106
- Relates to https://issues.redhat.com/browse/RHIDP-4968

fix: adjust startup, liveness and readiness probes settings

---

.github/workflows/bump-version.yml
.github/workflows/test.yml

The previous Python version (3.7) seems to no longer be available.
https://github.com/redhat-developer/rhdh-chart/actions/runs/12773187597/job/35604468404?pr=54

ci: Fix the python version used by `actions/setup-python`

---

.github/workflows/test.yml
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/ci/with-custom-dynamic-pvc-claim-spec-values.yaml
charts/backstage/templates/pvcs.yaml
charts/backstage/values.yaml

This PR extracts the dynamic plugins root PVC spec in a new `dynamicPlugins.cache.volumeClaimSpec` field in the values file.
This way, the whole PVC spec is configurable, including the storage class name, along with other things like the PVC size and access modes.
This should also help with https://issues.redhat.com/browse/RHIDP-5516 (make it possible to disable the dynamic plugin cache PVC and switch to an ephemeral volume).
- https://issues.redhat.com/browse/RHDHBUGS-156
- https://issues.redhat.com/browse/RHIDP-5573

fix: Make the dynamic plugins root PVC storage class configurable [RHDHBUGS-156][RHIDP-5573]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/README.md.gotmpl
charts/backstage/ci/with-custom-image-for-test-pod-values.yaml
charts/backstage/ci/with-test-pod-disabled-values.yaml
charts/backstage/templates/tests/test-connection.yaml
charts/backstage/values.yaml

This PR makes the test-connection pod image configurable.
As reported in https://issues.redhat.com/browse/RHDHBUGS-155, the fact that the image is hardcoded can be an issue in air-gapped environments.
Besides that, this PR also makes it possible to disable the creation of this test-connection pod. I've tested it and it doesn't prevent `helm test` from passing even with no test pod available.
- https://issues.redhat.com/browse/RHDHBUGS-155
- https://issues.redhat.com/browse/RHIDP-5558
* Disable the creation of the test pod and run `helm test`
```sh
$ helm upgrade --install my-backstage-1 charts/backstage --set route.enabled=false --set test.enabled=false
$ helm test my-backstage-1
[...]
NAME: my-backstage-1
LAST DEPLOYED: Tue Jan 14 18:28:25 2025
NAMESPACE: my-ns
STATUS: deployed
REVISION: …
```

fix: Fix hardcoded image for test connection pod and allow to skip the creation of this pod [RHDHBUGS-155] [RHIDP-5558]

---

.github/workflows/test.yml
ct.yaml

PRs (like #80) targetting release branches fail because the linter is configured to detect Chart changes compared to the `main` branch.
https://github.com/redhat-developer/rhdh-chart/actions/runs/13111112811/job/36575072460?pr=80

ci: Allow testing PRs targetting release branches

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Fix missing `auth.providers` config causing app startup to fail in `release-1.3`
- Fixes issues seen in https://github.com/redhat-developer/rhdh-chart/actions/runs/13112079983/job/36578033682?pr=86 and https://github.com/redhat-developer/rhdh-chart/actions/runs/13111723456/job/36576912437?pr=80 while trying to backport a few fixes to 1.3
- Related to https://github.com/redhat-developer/rhdh-chart/pull/46

fix: Fix missing `auth.providers` config causing app startup to fail in `release-1.3`

---

.github/workflows/test.yml
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/ci/with-custom-dynamic-pvc-claim-spec-values.yaml
charts/backstage/templates/pvcs.yaml
charts/backstage/values.yaml

Cherry-pick of #69 into `release-1.3`
- [issues.redhat.com/browse/RHDHBUGS-156](https://issues.redhat.com/browse/RHDHBUGS-156)
- https://issues.redhat.com/browse/RHIDP-5835

fix(release-1.3): Make the dynamic plugins root PVC spec configurable [RHDHBUGS-156][RHIDP-5835]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/ci/with-custom-dynamic-pvc-claim-spec-values.yaml
charts/backstage/templates/pvcs.yaml
charts/backstage/values.yaml

This makes the audit log PVC in 1.3 configurable, for the same reasons related to the dynamic plugins root PVC, as depicted in https://issues.redhat.com/browse/RHDHBUGS-135 (Helm upgrade failures) and https://issues.redhat.com/browse/RHIDP-5342 (cannot run 2 replicas).
Note that this fix is only for 1.3, as the audit log PVC has been removed in 1.4 (see https://github.com/redhat-developer/rhdh-chart/pull/47 - https://issues.redhat.com/browse/RHIDP-4852)
- Fixes https://issues.redhat.com/browse/RHIDP-5839
- Related to https://issues.redhat.com/browse/RHDHBUGS-135

fix(release-1.3): Make the audit log PVC configurable [RHIDP-5839]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.schema.json
charts/backstage/values.yaml

Sets the readOnlyRootFilesystem:true on the initContainer, has been tested with 1.3.x, 1.4.x, and next images
https://issues.redhat.com/browse/RHIDP-5886

Make initContainer root filesystem read-only

---

.github/workflows/test.yml
charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.yaml

When the DB PVC is initially created, it gets assigned the default storage class.
And it becomes impossible to upgrade the Helm Release later on because it looks like the (immutable) PVC is being patched after creation
Relates to https://issues.redhat.com/browse/RHIDP-5953

fix: Revert setting storage class fields to `null` by default [RHIDP-5953]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.yaml

When the dynamic plugins root, audit log and DB PVCs are initially created, they get assigned the default storage class.
And it becomes impossible to upgrade the Helm Release later on because it looks like these (immutable) PVCs are being patched after creation.
See the repro steps in the JIRA issue below.
Fixes https://issues.redhat.com/browse/RHIDP-5952

fix(release-1.3): Revert setting storage class fields to `null` by default [RHIDP-5952]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.yaml

When the dynamic plugins root and DB PVCs are initially created, they get assigned the default storage class.
And it becomes impossible to upgrade the Helm Release later on because it looks like these (immutable) PVCs are being patched after creation.
See the repro steps in the JIRA issue below.
Fixes https://issues.redhat.com/browse/RHIDP-5953

fix(release-1.4): Revert setting storage class fields to `null` by default [RHIDP-5953]

---

charts/backstage/Chart.yaml
charts/backstage/README.md

This bumps the Chart minor version on `main` to prevent version conflicts with fixes in `release-1.5`.
For example, the Chart version for this https://github.com/redhat-developer/rhdh-chart/pull/100 (cherry-pick PR) was the same as on the `main` branch.
&mdash;

chore: Bump Chart minor version to prevent version conflicts with fixes in `release-1.5`

---

charts/backstage/Chart.yaml
charts/backstage/README.md

GH Issues are disabled on this repo, but the support URLs metadata were mentioning it. THis fixes that, by pointing to JIRA instead.
&mdash;

chore: Fix the support URLs pointing to disabled GH issues

---

.github/workflows/release.yml

The release Workflow should not fail if the `charts/$chart_name/artifacthub-repo.yml` file does not exist.
https://github.com/redhat-developer/rhdh-chart/actions/runs/13922202704/job/38957872195

ci(release): Do not fail if the `artifacthub-repo.yml` file was not found in the chart

---

charts/orchestrator-infra/Chart.yaml
charts/orchestrator-infra/README.md
charts/orchestrator-infra/README.md.gotmpl
charts/orchestrator-infra/ci/upstream-olm-values.yaml
charts/orchestrator-infra/values.yaml

As reported  in https://github.com/redhat-developer/rhdh-chart/pull/102, when the pre-commit hooks run against the repo, they automatically end up updating the `charts/orchestrator-infra/README.md` file.
@coreydaley pointed out that `helm-docs` would use a default README template if there is none in the Chart folder.
This PR adds a custom README.md.gotmpl similar to the `charts/backstage` one: https://github.com/redhat-developer/rhdh-chart/blob/main/charts/backstage/README.md.gotmpl
It also makes sure that the field comments in the values.yaml are consistent, so that `helm-docs` can detect and add them to the generated README.md file.
https://issues.redhat.com/browse/RHIDP-6650
This is an example of how the generated README.md file looks like: …

fix(orchestrator-infra): Add missing `README.md.gotmpl` file to fix the pre-commit hooks  [RHIDP-6650]

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/values.yaml

Enable readOnlyRootFilesystem by default in the backend pod for RHDH 1.6
https://issues.redhat.com/browse/RHIDP-5892

chore: enable readOnlyRootFilesystem by default on backend container

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
charts/orchestrator-infra/Chart.yaml

If no chart has changed, it doesn't make sense to create a cluster then install OLM, so that `ct lint` and `ct install` would report that nothing has changed.
This PR speeds things up in such case by skipping these useless (but expensive) steps.

ci: Skip running some expensive steps (like cluster creation) if there are no changed charts

---

.github/workflows/lint.yaml
.github/workflows/test.yaml

This adds the missing Helm repos before running `ct lint`. This causes the lint failure observed in #127
Fixes https://github.com/redhat-developer/rhdh-chart/actions/runs/14398222155/job/40380952944#step:7:32

ci: Add missing Helm repos for the lint job to pass

---

charts/orchestrator-infra/Chart.yaml
charts/orchestrator-infra/README.md

This PR updates the Chart.yaml metadata for the orchestrator-infra chart to avoid conflicts with the main Red Hat Developer Hub (RHDH) chart in Quay and Helm search results.
Why this change is needed: The original metadata reused several fields (e.g. name, charts.openshift.io/name, description) from the RHDH chart, which caused ambiguity and potential collisions when both charts were published as OCI artifacts.
Related issue: https://issues.redhat.com/browse/RHIDP-6169
For example, the orchestrator-infra-chart artifact in quay:
```bash
annotations:
charts.openshift.io/archs: x86_64
charts.openshift.io/name: Red Hat Developer Hub (CI Build)
charts.openshift.io/provider: Red Hat
charts.openshift.io/supportURL: https://access.redhat.com/support
apiVersion: v2
appVersion: 1.6.0
description: A …
```

chore(chart): fix Orchestrator Infra Chart metadata to avoid conflicts with RHDH Chart

---

.github/workflows/snyk.yaml

This PR updates the snyk.yaml GitHub Actions workflow to include IaC scanning of the orchestrator-infra Helm chart in addition to the existing backstage chart.
https://issues.redhat.com/browse/RHIDP-6630 
Added helm dependency build and helm template for charts/orchestrator-infra.
Added a separate Snyk IaC scan step targeting the rendered output of orchestrator-infra.
Ensures both backstage and orchestrator-infra templates are scanned weekly for infrastructure vulnerabilities.

chore: enable Snyk scan for orchestrator-infra chart

---

.github/workflows/snyk.yaml

Refactors the GitHub Actions Snyk workflow to use a [matrix job](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow) strategy,
allowing independent IaC scans for `backstage` and `orchestrator-infra`
charts with minimal duplication.
https://issues.redhat.com/browse/RHIDP-6630
- Adds matrix entries for each chart path/output
- Uses full commit SHA to pin snyk/actions/iac for security
- Prepares workflow for easier scaling as more charts are added

chore(ci): simplify Snyk workflow using matrix for chart scans

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/README.md.gotmpl

chore: set correct minimum k8s version based on OCP 4.14
N/A
N/A (or see commit message above for issue number)
N/A
As the author of this Pull Request I made sure that:

chore: set correct minimum k8s version based on OCP 4.14

---

.rhdh/scripts/install.sh

chore: for now, comment out the non-working chart repo install stuff until we have this implemented again in RHIDP-6668
Signed-off-by: RHDH Build (rhdh-bot) <rhdh-bot@redhat.com>
N/A
N/A (or see commit message above for issue number)
N/A
As the author of this Pull Request I made sure that:

chore: for now, comment out the non-working chart repo install stuff until we have this implemented again in RHIDP-6668

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/README.md.gotmpl

This PR will close the outstanding issues addressed in this [doc bug](https://issues.redhat.com/browse/RHIDP-7255).

fix: documentation bug for backstage chart readme, in orchestrator

---

charts/backstage/Chart.yaml
charts/backstage/README.md
charts/backstage/README.md.gotmpl
charts/backstage/values.schema.json
charts/backstage/values.yaml

This PR will close [this ticket](https://issues.redhat.com/browse/RHIDP-7458) by enableing serverless operator and serverlessLogic operator by default in the helm chart values. 
Note that the operators will still be deployed conditionally, as 'Orchestrator' needs to be enabled in order to trigger their deployment.

enabling serverless+serverlessLogic by default

---

.rhdh/scripts/install.sh

https://github.com/redhat-developer/rhdh-chart/pull/152 introduced the automatic generation of a `HelmChartRepository` Resource in the cluster, but the problem is that it does not support neither OCI artifacts nor `file` references in its `connectionConfig`. It only supports repos served over HTTP.
This PR extends this approach by also deploying an in-cluster (not exposed publicly) web server that serves the necessary Helm repo files (index.yaml and chart archive from the OCI artifact).
With this, the corresponding chart CI version now shows up in the list on the OCP console, and it is possible to upgrade via the web console after deploying the Chart via CLI.
Ref: https://issues.redhat.com/browse/RHIDP-7251
Ref: https://issues.redhat.com/browse/RHIDP-6668
/cc @nickboldt @Omar-AlJaljuli …

chore(CI builds): Expose an in-cluster Helm repo off of the OCI chart pulled

---

charts/backstage/Chart.yaml
charts/backstage/README.md

chore: update default chart settings using downstream patches so we can remove Chart_patch.yaml (RHIDP-7529)
N/A
N/A (or see commit message above for issue number)
N/A
As the author of this Pull Request I made sure that:

chore: update default chart settings using downstream patches so we can remove Chart_patch.yaml (RHIDP-7529)

---

.github/workflows/pre-commit.yaml
OWNERS

Similar to https://github.com/redhat-developer/rhdh-operator/pull/1243, this reviews and updates the owners file and authorize jobs with a relevant list of people, including the current Install group members.
&mdash;

chore: Review and update owners file and authorize jobs with the current Install group members

---

.github/pull_request_template.md

This PR mainly updates the PR Template checklist to include a reminder to check the Knative CRDs versions if needed.
This is the first step until we can enforce that check automatically.
Relates to https://issues.redhat.com/browse/RHIDP-6694

chore: Update PR Template checklist with reminder to check the `orchestrator-infra` CRDs versions [RHIDP-6694]

---

.github/workflows/lint.yaml
.github/workflows/test.yaml

This is a follow-up to [1], to ensure that they work properly with Python 3.14 - see [2]
[1] https://github.com/redhat-developer/rhdh-chart/pull/249
[2] https://github.com/redhat-developer/rhdh-chart/actions/runs/18350355942/job/52268343561?pr=248
&mdash;

chore(deps): Bump the versions of the tools installed by `helm/chart-testing-action`
