redhat-developer/rhdh-chart

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/artifacthub-repo.yml
chore: enable Verified Publisher notation on new chart at artifacthub.io - https://artifacthub.io/docs/topics/repositories/#verified-publisher
Signed-off-by: rhdh-bot service account <rhdh-bot@redhat.com>
N/A
[RHIDP-1020](https://issues.redhat.com/browse/RHIDP-1020) 
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
> chore: enable Verified Publisher notation on new chart

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
chore: fix instructions/readmes/URLs
N/A
RHIDP-1020
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
> chore: fix instructions/readmes/URLs

- README.md
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
chore(doc) fix readmes to refer to newer helm and k8s versions; fix inconsistent instance naming (RHIDP-976)
bump to 2.15.0
N/A
https://issues.redhat.com/browse/RHIDP-976
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
> chore(doc) fix readmes to refer to newer helm and k8s versions; fix inconsistent instance naming (RHIDP-976)

- .github/workflows/release.yml
Updated to use new GH Actions env syntax. No impact on Chart.
> chore(ci): tidy up actions

- README.md
- charts/backstage/Chart.yaml
Added the telemetry opt-in banner to the following files: `README.md` and `charts/backstage/Chart.yaml`
Closes https://issues.redhat.com/browse/RHIDP-1906
> added telemetry opt-in banner

- docs/external-db.md
Add docs/external-db.md 
https://issues.redhat.com/browse/RHIDP-2016
> Add external-db.md doc

- .github/workflows/release.yml
This PR manually updates the action to use the latest release of [oras-project/setup-oras@v1.2.0](https://github.com/oras-project/setup-oras/releases/tag/v1.2.0). 
The new release uses Node.js 20 and therefore will remediate the deprecation warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: oras-project/setup-oras@ee7dbe1144cb00080a89497f937dae78f85fce29
> chore(ci): update setup-oras to latest release

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
> Remove dist/static mount

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
> RHIDP-3260: rename dynamic plugins npmrc secret

- charts/backstage/Chart.yaml
- charts/backstage/README.md
> chore: tagRelease.sh: bump to 1.4 in main branch

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/templates/pvcs.yaml
- charts/backstage/values.schema.json
- charts/backstage/values.yaml
https://issues.redhat.com/browse/RHIDP-4922
> feature: Remove Audit Log PVC

- charts/backstage/Chart.yaml
- charts/backstage/README.md
> chore: tagRelease.sh: bump to 1.5 in main branch

- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/README.md.gotmpl
- charts/backstage/ci/with-custom-image-for-test-pod-values.yaml
- charts/backstage/ci/with-test-pod-disabled-values.yaml
- charts/backstage/templates/tests/test-connection.yaml
- charts/backstage/values.yaml
Cherry-pick of #54 
- https://issues.redhat.com/browse/RHDHBUGS-155
- https://issues.redhat.com/browse/RHIDP-5837
> fix(release-1.3): Fix hardcoded image for test connection pod and allow to skip the creation of this pod [RHDHBUGS-155][RHIDP-5837]

- .github/workflows/test.yml
- charts/backstage/Chart.yaml
- charts/backstage/README.md
- charts/backstage/ci/with-custom-dynamic-pvc-claim-spec-values.yaml
- charts/backstage/templates/pvcs.yaml
- charts/backstage/values.yaml
Cherry-pick of #69
- Fixes https://issues.redhat.com/browse/RHIDP-5836
> fix(release-1.4): Make the dynamic plugins root PVC configurable [RHDHBUGS-156][RHIDP-5836]

- charts/backstage/Chart.yaml
- charts/backstage/README.md
> Updates sources section of Chart.yaml to reflect repository migrations

- .github/workflows/test.yml
This is in preparation for testing the orchestrator-infra chart that installs some Operators. This paves the way to fixing the failures seen in https://github.com/redhat-developer/rhdh-chart/actions/runs/13789045608/job/38570057715?pr=108
https://issues.redhat.com/browse/RHIDP-6159
> ci: Install OLM in the test K8s cluster

- .github/workflows/pre-commit.yaml
This PR makes sure to run the pre-commit checks on all files.
For some reason, they used to skip the files to check.
Ideally, the workflow could auto-push the changes after the pre-commit run, but that could come up later.
&mdash;
> ci: Fix the pre-commit checks

- .github/workflows/lint.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/test.yaml
Otherwise, they will be stuck as Pending in the list of checks on the PR view
> ci: Always run the required PR checks

- .github/workflows/pre-commit.yaml
Addendum to https://github.com/redhat-developer/rhdh-chart/pull/148
> ci: Fix pre-commit diff check command

- .rhdh/docs/installing-ci-charts.adoc
- .rhdh/scripts/install.sh
chore: include doc+script for installing RHDH 1.6 (RHIDP-1477, RHIDP-6668, RHIDP-7251) - partial pick from main [release-1.6]
N/A
N/A (or see commit message above for issue number)
N/A
As the author of this Pull Request I made sure that:
> chore: include doc+script for installing RHDH 1.6 (RHIDP-1477, RHIDP-6668, RHIDP-7251) - partial pick from main [release-1.6]
